apiVersion: apps/v1
kind: Deployment
metadata:
  name: professor-tecadm-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: professor-tecadm
  template:
    metadata:
      labels:
        app: professor-tecadm
    spec:
      containers:
        - name: professor-tecadm-service
          image: distrischool-professor-tecadm-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL # Padrão Spring Boot
              value: "jdbc:postgresql://postgres-service:5432/professortecadm_db" # Valor do seu .env/application-dev
            - name: SPRING_DATASOURCE_USERNAME # Padrão Spring Boot
              value: "admin" # Valor do seu .env/application-dev
            - name: SPRING_DATASOURCE_PASSWORD # Padrão Spring Boot
              value: "admin" # Valor do seu .env/application-dev
            - name: SPRING_RABBITMQ_HOST # Padrão Spring Boot
              value: "rabbitmq-service"
            - name: SPRING_RABBITMQ_PORT # Padrão Spring Boot
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME # Padrão Spring Boot
              value: "admin" # Valor do seu .env
            - name: SPRING_RABBITMQ_PASSWORD # Padrão Spring Boot
              value: "admin" # Valor do seu .env
