# Nome da Aplicação (Configuração comum a todos os ambientes)
spring.application.name=distrischool-professor-tecadm-service

# Ativa o perfil 'dev' por padrão ao rodar localmente.
spring.profiles.active=dev