CREATE TABLE professores (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             nome VARCHAR(255) NOT NULL,
                             email VARCHAR(255) NOT NULL UNIQUE,
                             especialidade VARCHAR(255),
                             data_contratacao DATE NOT NULL
);