CREATE TABLE tecnicos_administrativos (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          nome VARCHAR(255) NOT NULL,
                                          email VARCHAR(255) NOT NULL UNIQUE,
                                          cargo VARCHAR(255) NOT NULL,
                                          data_contratacao DATE NOT NULL
);