-- V1__criar_tabela_aluno.sql
CREATE TABLE aluno (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    matricula VARCHAR(50) UNIQUE NOT NULL,
    turma VARCHAR(50) NOT NULL,
    contato VARCHAR(50),
    data_nascimento DATE,
    endereco_rua VARCHAR(255),
    endereco_numero VARCHAR(20),
    endereco_cep VARCHAR(20),
    endereco_cidade VARCHAR(255),
    endereco_estado VARCHAR(2)
);