apiVersion: apps/v1
kind: Deployment
metadata:
  name: aluno-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aluno
  template:
    metadata:
      labels:
        app: aluno
    spec:
      containers:
        - name: aluno-service
          image: distrischool-aluno-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            # --- Configurações de Banco de Dados ---
            - name: SPRING_DATASOURCE_URL # <<< Nome padrão Spring
              value: "jdbc:postgresql://postgres-service:5432/distrischool_db" # <<< Banco unificado
            - name: SPRING_DATASOURCE_USERNAME # <<< Nome padrão Spring
              value: "postgres" # <<< Credencial correta
            - name: SPRING_DATASOURCE_PASSWORD # <<< Nome padrão Spring
              value: "postgres" # <<< Credencial correta
            # --- Configurações de Schema ---
            - name: SPRING_FLYWAY_SCHEMAS
              value: "aluno_schema" # <<< Schema específico
            - name: SPRING_FLYWAY_CREATE_SCHEMAS
              value: "true"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA
              value: "aluno_schema" # <<< Schema específico

            # --- Configurações do RabbitMQ ---
            - name: SPRING_RABBITMQ_HOST # <<< Nome padrão Spring
              value: "rabbitmq-service"
            - name: SPRING_RABBITMQ_PORT # <<< Nome padrão Spring
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME # <<< Nome padrão Spring
              value: "admin" # <<< Credencial correta
            - name: SPRING_RABBITMQ_PASSWORD # <<< Nome padrão Spring
              value: "admin" # <<< Credencial correta